<a href="https://colab.research.google.com/github/Erbaz/pytorch_dl/blob/main/Pytorch_3_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#Introduction to Tensors

## Types of Tensors
1. Scalars (0-dimension)
2. Vectors (1-dimension)
3. Matrix (2-dimension)
4. Tensor (n-dimension)

In [6]:
#scalar tensors
scalar = torch.tensor(7)
scalar.ndim # no. of dimensions


0

In [5]:
scalar.item() # give the tensor back as the number int


7

In [7]:
# vector tensors
vector = torch.tensor([7,8])

In [11]:
vector.ndim  # no. of dimensions

1

In [12]:
vector.shape

torch.Size([2])

In [13]:
# matrix tensors
matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
matrix.ndim

2

In [16]:
matrix[0] # refers to the FIRST row of the matrix

tensor([7, 8])

In [17]:
matrix.shape # 2x2 matrix

torch.Size([2, 2])

In [22]:
matrix3x3 = torch.tensor([[1,2,3],
                        [4,5,6],
                        [7,8,9]])

matrix3x3

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [24]:
matrix3x3.ndim

2

In [23]:
matrix3x3.shape

torch.Size([3, 3])

In [19]:
# tensor
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [20]:
tensor.ndim

3

In [21]:
tensor.shape

torch.Size([1, 3, 3])

### Explanation to the shape of tensors:
We have defined `tensor` to represent a 3x3 matrix within a tensor. The tensor is defined with the number of axis it has. You can compare with the `matrix3x3` that it has 2 dimensions while `tensor` has 3.

If you observe, from the previous types of tensors, you can now see a pattern:

the number of square brackets right after the parentheses defines the dimensions the tensor has. Therefore: \
scalars: `(` = no square brackets = 0 dimensions \
vectors: `([` = 1 square brackets = 1 dimension\
matrix: `([[` = 2 square brackets = 2 dimensions\
3d tensors: `([[[`  = 3 square brackets = 3 dimensions