<a href="https://colab.research.google.com/github/Erbaz/pytorch_dl/blob/main/Pytorch_4_Random_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Random Tensors

### Why random tensors?
Random tensors are important because the way many neural networks learn is by using tensors with random values and adjusting them weights to get desired results.


In [2]:
import torch

random_tensor = torch.rand(3,4) # generates a tensor of 3 ROWS and 4 COLUMNS

random_tensor

tensor([[0.1524, 0.6534, 0.3131, 0.7667],
        [0.9357, 0.2031, 0.3228, 0.0537],
        [0.6462, 0.7693, 0.9844, 0.2385]])

In [ ]:
random_tensor.ndim

In [9]:
next_random_tensor = torch.rand(1,2)
next_random_tensor

tensor([[0.2893, 0.3613]])

In [15]:
new_random_tensor = torch.rand(3)
new_random_tensor

tensor([0.9492, 0.1257, 0.1405])

In [7]:
another_random_tensor = torch.rand(2,3,4) # generates a tensor with 3 dimensions
another_random_tensor

tensor([[[0.2439, 0.3614, 0.0657, 0.5954],
         [0.6546, 0.2361, 0.2564, 0.5721],
         [0.6950, 0.5843, 0.1380, 0.6417]],

        [[0.3946, 0.5626, 0.0212, 0.5910],
         [0.4555, 0.9372, 0.6412, 0.5170],
         [0.0939, 0.7048, 0.4952, 0.0576]]])

Observe how `torch.rand(3,4)` and `torch.rand(1,2)` gave a default dimension of 2.\
While `torch.rand(3)` gave a default dimension of 1. \
To define a tensor with the dimensions you need, you use the parameters in the sequence:\
`torch.rand(no_of_dimensions, rows, columns)`



In [16]:
# representing an image size with tensors
image_tensor = torch.rand(3, 244 , 244) # no_of_color_channels, pixel width, pixel height
image_tensor

tensor([[[0.6985, 0.5996, 0.2535,  ..., 0.6622, 0.2869, 0.2258],
         [0.4577, 0.9974, 0.0541,  ..., 0.4404, 0.0813, 0.5355],
         [0.1948, 0.8790, 0.8622,  ..., 0.5192, 0.6327, 0.4856],
         ...,
         [0.8790, 0.9515, 0.2826,  ..., 0.3210, 0.4414, 0.4769],
         [0.1170, 0.6997, 0.8248,  ..., 0.5180, 0.9027, 0.2853],
         [0.7588, 0.8074, 0.7582,  ..., 0.3121, 0.4305, 0.8759]],

        [[0.5717, 0.1212, 0.7628,  ..., 0.9265, 0.2553, 0.6331],
         [0.3201, 0.9148, 0.7925,  ..., 0.5488, 0.1794, 0.2742],
         [0.7044, 0.0493, 0.6402,  ..., 0.6986, 0.1115, 0.7653],
         ...,
         [0.1856, 0.8520, 0.0442,  ..., 0.7988, 0.5205, 0.3404],
         [0.4819, 0.5173, 0.2534,  ..., 0.5279, 0.5541, 0.0201],
         [0.0027, 0.9647, 0.1507,  ..., 0.7825, 0.8430, 0.9788]],

        [[0.6731, 0.4310, 0.2297,  ..., 0.6365, 0.2572, 0.9577],
         [0.9697, 0.4426, 0.9406,  ..., 0.4128, 0.1196, 0.2196],
         [0.7755, 0.7499, 0.1776,  ..., 0.9948, 0.1466, 0.