<a href="https://colab.research.google.com/github/Erbaz/pytorch_dl/blob/main/Pytorch_5_Creating_Different_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Zeros and ones
Are used to perform things like:
1. masking
2. discrete data analysis
3. padding


In [1]:
import torch

# Create a tensor of all zeros
zeros = torch.zeros(3,4)

# Create a tensor of all ones
ones = torch.ones(4,4)

zeros, ones

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [ ]:
random_tensor = torch.rand(5,5)
random_tensor

tensor([[0.4784, 0.1168, 0.8172, 0.6848, 0.9256],
        [0.1276, 0.2479, 0.3679, 0.1617, 0.9306],
        [0.5035, 0.7690, 0.3469, 0.4459, 0.7245],
        [0.1827, 0.2400, 0.8020, 0.0178, 0.1244],
        [0.9928, 0.5278, 0.5924, 0.3812, 0.5837]])

In [ ]:
# Suppose we wish to mask the matrix

mask = torch.zeros(5, 5)
masked_tensor = mask * random_tensor

masked_tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [2]:
# The default datatype of values is float 32
ones.dtype, zeros.dtype

(torch.float32, torch.float32)

# Creating Tensors With Range

In [3]:
one_to_ten = torch.arange(start=1, end=11, step=1) # generate vector with from 1 to 10 with incremental of 1
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
one_to_ten_half_step = torch.arange(start=1, end=11, step=0.5) # generate vector with from 1 to 10 with incremental of 0.5
one_to_ten_half_step

tensor([ 1.0000,  1.5000,  2.0000,  2.5000,  3.0000,  3.5000,  4.0000,  4.5000,
         5.0000,  5.5000,  6.0000,  6.5000,  7.0000,  7.5000,  8.0000,  8.5000,
         9.0000,  9.5000, 10.0000, 10.5000])

# Creating Tensors Like

In [7]:
# If you want to copy the size of a tensor (such as creating a mask), you use zeros_like()
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
mask_one_to_ten_half_step = torch.zeros_like(one_to_ten_half_step)
mask_one_to_ten_half_step

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])