<a href="https://colab.research.google.com/github/Erbaz/pytorch_dl/blob/main/Pytorch_12_Device_Agnostic_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
# Check device
!nvidia-smi

Wed Apr 24 12:26:30 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   64C    P8              13W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [4]:
# Create a Tensor
tensor = torch.rand(2,3)
print(tensor)
print(tensor.device) # using default cpu

tensor([[0.1931, 0.4499, 0.3887],
        [0.0008, 0.0882, 0.6090]])
cpu


In [6]:
# Check Cuda device count
print(f"device count: {torch.cuda.device_count()}")

# Lets write Device Agnostic case
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"device: {device}")

tensor = torch.rand(2,3, device=device)

tensor # uses gpu if available


device count: 1
device: cuda


tensor([[0.2380, 0.0700, 0.5623],
        [0.3321, 0.6155, 0.3647]], device='cuda:0')

In [7]:
# Tensor on GPU cannot be tranformed into NumPy

tensor.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [9]:
# Therefore we will have to move Tensor to CPU
tensor_cpu = tensor.cpu()
tensor_cpu.numpy()

array([[0.23799044, 0.07001086, 0.56230766],
       [0.33211014, 0.61554044, 0.3646517 ]], dtype=float32)