<a href="https://colab.research.google.com/github/Erbaz/pytorch_dl/blob/main/Pytorch_6_Tensor_Datatypes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tensor Datatypes


In [2]:
import torch

# Default datatype of a tensor is float32

tensor_default = torch.rand(2, 3, 3)
tensor_default.dtype # dtype is a getter to obtain the datatype of the tensor


torch.float32

In [ ]:
# Creating a tensor with a diffetent dtype is possible

tensor_f16 = torch.tensor([3, 6, 9], dtype=torch.float16 )
tensor_f16.dtype

torch.float16

`float32` stores each value using 32 bits. It is referred to as single-precision. \

`float16` stores each value using 16 bits. It is referred to as half-precion



In [ ]:
# Changing datatypes
tensor_f16_convert = tensor_default.type(torch.float16)

tensor_f16_convert

tensor([[[0.2817, 0.5752, 0.3889],
         [0.1065, 0.1301, 0.0754],
         [0.2395, 0.2732, 0.7812]],

        [[0.0624, 0.6738, 0.2349],
         [0.3135, 0.3560, 0.7593],
         [0.6636, 0.4866, 0.4473]]], dtype=torch.float16)

# Main Tensor Params
1. datatype
2. shape
3. device

Tensors must be of the same datatype to perform operations amongst themselves. Mismatch in datatypes leads to error as precisions cannot be reconciled. \

Tensors need to be of the right shape to operate with other tensors. Such as in masking, you require zeros tensor to be of the same shape as the targeted tensor. \

Tensors need to be on the same device to be computed. If one is on a `cpu` while the other is on a `cuda` then there will be a referrence error.

In [ ]:
new_tensor = torch.tensor([1,2,3], # shape of the tensor. In this case it is 1x1x3
                          dtype=None, # defaults to torch.float32
                          device=None, # defaults to system device (cpu in this case)
                          requires_grad=False # wether or not gradient for tensor needs to be computed
                          )
new_tensor.shape, new_tensor.dtype, new_tensor.device

(torch.Size([3]), torch.int64, device(type='cpu'))

# Observations

## Datatypes Do Not Always Cause Problems In Computation
Integers and Float tensors can be multiplied with one another, for example, because the operation just converts the memory values to that of the float tensor.

In [4]:
# Caveat To Observe

int32_tensor = torch.tensor([1,2,3], dtype=torch.int32)
int64_tensor = torch.tensor([1,4,2], dtype=torch.int64)
float32_tensor = torch.tensor([3,2,2.4], dtype=torch.float32)
float16_tensor = torch.tensor([.4, .5, .05], dtype=torch.float16)

print(int32_tensor * int64_tensor)
print(float32_tensor * float16_tensor)
print(float16_tensor * int64_tensor)

tensor([1, 8, 6])
tensor([1.1997, 1.0000, 0.1200])
tensor([0.3999, 2.0000, 0.1000], dtype=torch.float16)


## Size And Shape Of Tensor Are The Same Object
`size()` is the method, while `shape` is the attribute. Both contain the same information.

In [6]:

bTensor = torch.rand(3,2)
if(bTensor.size() == bTensor.shape):
  print("size() and shape are the same thing")
else:
  print("size() and shape are NOT the same thingg")



size() and shape are the same thing
