<a href="https://colab.research.google.com/github/Erbaz/pytorch_dl/blob/main/Pytorch_7_Tensor_Manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

# Basic Operations Performed On Tensors

- Addition
- Subtraction
- Multiplication (element-wise)
- Division

In [ ]:
# Addition

tensor = torch.rand(3,1)
print(f"initial tensor:\n {tensor}")
print(f"after addition:\n {tensor + 10}")

initial tensor:
 tensor([[0.3055],
        [0.4075],
        [0.5712]])
after addition:
 tensor([[10.3055],
        [10.4075],
        [10.5712]])


In [ ]:
# Multiplication
print(f"after multiplication with 10: \n{tensor * 10}")

after multiplication with 10: 
tensor([[3.0549],
        [4.0745],
        [5.7118]])


In [ ]:
#  Subtraction
print(f"after subtraction with 10: \n{tensor - 10}")

after subtraction with 10: 
tensor([[-9.6945],
        [-9.5925],
        [-9.4288]])


In [ ]:
# Division
print(f"after division with 10:\n{tensor / 10}")

after division with 10:
tensor([[0.0305],
        [0.0407],
        [0.0571]])


In [ ]:
# Using inbuilt functions
print(f"multiplication: \n {torch.mul(tensor, 10)}")
print(f"addition: \n {torch.add(tensor, 10)}")
print(f"subtraction: \n {torch.sub(tensor, 0.2)}")
print(f"division: \n {torch.div(tensor, 10)}")

multiplication: 
 tensor([[3.0549],
        [4.0745],
        [5.7118]])
addition: 
 tensor([[10.3055],
        [10.4075],
        [10.5712]])
subtraction: 
 tensor([[0.1055],
        [0.2075],
        [0.3712]])
division: 
 tensor([[0.0305],
        [0.0407],
        [0.0571]])


#Matrix Multiplication

## Explanation
Basically, when we multiply two matrices with one another, we are multiplying each row of one matrix to the column of the other and adding the results of the elements for each row-column combination. This results in what is called a **"Dot Product"** for each row-column combination. Once all dot products are found, we get a matrix of those dot products which is the final result of the multiplication of the two matrices.

The rule for multiplication is that the row length of one matrix must match the column length of the other. And similarly the column length of one matrix must match the row length of the other matrix.

Here is a link for further explanation:
https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [5]:
# Multiplying two tensors (dimension - 1) together vs Using matmul()

tensor = torch.rand(3) # a tensor of one row and 3 columns
print(f"starting tensor: {tensor}")

multiplicationResult = tensor * tensor
print(f"tensor * tensor = {multiplicationResult}")

multiplicationResult2 = torch.matmul(tensor, tensor)

print(f"torch.matmul(tensor , tensor) {multiplicationResult2}")

# The difference between the results is due to the fact that matmul produces a dot product of the multiplication
# while the direct multiplication produces element-wise multiplication


starting tensor: tensor([0.8590, 0.8478, 0.9558])
tensor * tensor = tensor([0.7379, 0.7187, 0.9136])
torch.matmul(tensor , tensor) 2.370257616043091


In [12]:
# Multiplying higher dimension tensors together
# It is important to make sure that - when multiplying - the shapes are congruent
# If tensor1 has shape: (m,n) then tensor2 must have shape: (n,m)

tensor1 = torch.rand(3,2)
tensor2 = torch.rand(2,3)

# Element-Wise Multiplication cannot be performed as this will cause error because sizes of the tensors do not match
print(f"size of tensor 1: {tensor1.size()}")
print(f"size of tensor 2: {tensor2.size()}")

# However, dot product can be produced
dotProd = torch.matmul(tensor1, tensor2)

print(f"multiplicatin result: {multiplicationResult}")
print(f"dot product:\n {dotProd}")

size of tensor 1: torch.Size([3, 2])
size of tensor 2: torch.Size([2, 3])
multiplicatin result: tensor([[0.2064, 0.2582],
        [0.3792, 0.4744]])
dot product:
 tensor([[0.4005, 0.7296, 0.5575],
        [0.3410, 0.5958, 0.4749],
        [0.1606, 0.2640, 0.2238]])


### Short-Hand For torch.matmul()

In [14]:
dotProd = tensor1 @ tensor2
print(dotProd)

#Also
dotProd = torch.mm(tensor1, tensor2)
dotProd

tensor([[0.4005, 0.7296, 0.5575],
        [0.3410, 0.5958, 0.4749],
        [0.1606, 0.2640, 0.2238]])


tensor([[0.4005, 0.7296, 0.5575],
        [0.3410, 0.5958, 0.4749],
        [0.1606, 0.2640, 0.2238]])

### Transpose

A transpose basically switches the axis of the tensor where by its shape of (m,n) changes to (n,m)

In [18]:
tensor = torch.rand(3,2)

# We cannot multiply tensor via matmul() due to the shape
# Therefore we apply transpose: tensor.T
print(tensor.T.shape)
print(tensor @ tensor.T)
print((tensor @ tensor.T).shape)
print(tensor.T @ tensor)
print((tensor.T @ tensor).shape)





torch.Size([2, 3])
tensor([[0.4809, 0.3729, 0.5480],
        [0.3729, 0.3308, 0.3952],
        [0.5480, 0.3952, 0.6456]])
torch.Size([3, 3])
tensor([[0.6035, 0.6540],
        [0.6540, 0.8538]])
torch.Size([2, 2])
