<a href="https://colab.research.google.com/github/Erbaz/pytorch_dl/blob/main/Pytorch_10_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch, numpy as np

# NumPy

NumpPy is a numerical computing library for Python. Hence Pytorch can utilize it.

In [3]:
# NumPy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # .from_numpy() will make a new (copy) tensor from the numpy array
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [15]:
# default dtypes for numpy arrays and tensors is different
# numpy's default is float64
# torch's default is float32
array.dtype , torch.arange(1.0,8.0).dtype

(dtype('float64'), torch.float32)

In [13]:
tensor.type(torch.float32).dtype # we can change dtype of tensor

torch.float32

In [22]:
# Tensor to NumPy array
tensor = torch.arange(1.0, 8.0) # default dtype is 32
numpy_array = tensor.numpy()
tensor, tensor.dtype, numpy_array, numpy_array.dtype

(tensor([1., 2., 3., 4., 5., 6., 7.]),
 torch.float32,
 array([1., 2., 3., 4., 5., 6., 7.], dtype=float32),
 dtype('float32'))