<a href="https://colab.research.google.com/github/Erbaz/pytorch_dl/blob/main/Pytorch_9_Indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

#Indexing

### Chained Indexing

In [55]:
tensor = torch.rand(3,4)
tensor

tensor([[0.2903, 0.5689, 0.7963, 0.2225],
        [0.3475, 0.0375, 0.5530, 0.1101],
        [0.6782, 0.9759, 0.5597, 0.5865]])

In [56]:
tensor[0]

tensor([0.2903, 0.5689, 0.7963, 0.2225])

In [53]:
tensor[1][0]

tensor([0.6615, 0.1986, 0.8034, 0.1091])

In [57]:
tensor[1]

tensor([0.3475, 0.0375, 0.5530, 0.1101])

In [54]:
tensor[0][0] # selects the first row as a 1D tensor, and then selects the 0th index of that 1D tensor

tensor([0.8097, 0.9329, 0.1407, 0.4361])

In [36]:
tensor[0][1]

tensor(0.7180)

In [39]:
tensor[0][1:3] # selects the first row, and then selects the second to the third rows of the resulting tensor

tensor([0.7180, 0.4357])

In [44]:
tensor[0:2][0:2] # selects the first two rows, and then selects the first two rows of the resulting tensor

tensor([[0.1408, 0.7180, 0.4357, 0.3874],
        [0.9111, 0.5615, 0.5857, 0.7622]])

In [48]:
tensor[0:2][1] # selects the first two rows, and then selects the second row of the resulting tensor

tensor([0.9111, 0.5615, 0.5857, 0.7622])

### Multidimensional Indexing

In [38]:
tensor[0,0] # selects the values in row 0 and column 0 (first value)

tensor(0.1408)

In [30]:
tensor[0:2,0:2] # selects the values in row 0 to 1 and the columns 0 to 1

tensor([[0.1000, 0.2000],
        [0.6000, 0.7000]])

In [49]:
tensor[0:2, 1] # selects the first two rows and the first column of the resulting tensor

tensor([0.7180, 0.5615])

### Further Practice

In [60]:
tensor = torch.rand(2,3,4)
tensor, tensor.shape

(tensor([[[0.0869, 0.6880, 0.6181, 0.9139],
          [0.7680, 0.0219, 0.9779, 0.4213],
          [0.8455, 0.5312, 0.5220, 0.8432]],
 
         [[0.2216, 0.5779, 0.5405, 0.6806],
          [0.4388, 0.0831, 0.5042, 0.0878],
          [0.9309, 0.1183, 0.5381, 0.8152]]]),
 torch.Size([2, 3, 4]))

In [61]:
# first row of the 1st dimension
tensor[0]

tensor([[0.0869, 0.6880, 0.6181, 0.9139],
        [0.7680, 0.0219, 0.9779, 0.4213],
        [0.8455, 0.5312, 0.5220, 0.8432]])

In [62]:
# second row of the 1st dimension
tensor [1]

tensor([[0.2216, 0.5779, 0.5405, 0.6806],
        [0.4388, 0.0831, 0.5042, 0.0878],
        [0.9309, 0.1183, 0.5381, 0.8152]])

In [68]:
# first row of the first row of the 1st dimension
tensor[0][0]

tensor([0.0869, 0.6880, 0.6181, 0.9139])

In [70]:
# first row and first column of the 1st dimension
tensor[0,0]

tensor([0.0869, 0.6880, 0.6181, 0.9139])

In [73]:
tensor[1][1]

tensor([0.4388, 0.0831, 0.5042, 0.0878])

In [72]:
tensor[1,1]

tensor([0.4388, 0.0831, 0.5042, 0.0878])

In [75]:
tensor[1][1][1]

tensor(0.0831)

In [74]:
tensor[1,1,1]

tensor(0.0831)

In [77]:
tensor[:,1]

tensor([[0.7680, 0.0219, 0.9779, 0.4213],
        [0.4388, 0.0831, 0.5042, 0.0878]])