<a href="https://colab.research.google.com/github/Erbaz/pytorch_dl/blob/main/Pytorch_11_Reproducibility.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

# Reproducibility

How a neural network learns:
1. Start with a random number
2. tensor operations
3. update random numbers and adjust weights
4. repeat 3 and make it better
5. repeat 4 and make it better
6. and on and on...


To reduce the randomeness in neural networks, we make use of the concept of a **random seed**. Which essentially adds "flavour" to the randomness

In [2]:
# create 2 random tensor

tensorA = torch.rand(3,4)
tensorB = torch.rand(3,4)
print(tensorA)
print(tensorB)
print(tensorA == tensorB) # tensorA and tensorB are highly unlikely to be the sameµ

tensor([[0.4910, 0.2646, 0.1169, 0.9578],
        [0.2983, 0.9181, 0.6366, 0.7486],
        [0.4361, 0.6500, 0.2628, 0.7713]])
tensor([[0.3459, 0.7134, 0.6853, 0.8482],
        [0.5015, 0.9458, 0.5941, 0.9010],
        [0.4826, 0.7598, 0.3337, 0.3504]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [11]:
# create random but reproducible tensors
RAND_SEED = 36 # can be any number (int or float)
torch.manual_seed(RAND_SEED) # manual seed is set
tensorA = torch.rand(3,4)
torch.manual_seed(RAND_SEED) # manual seed is re-set (necessary)
tensorB = torch.rand(3,4)
print(f"Random Seed: {RAND_SEED} of type: {type(RAND_SEED)}")
print(tensorA)
print(tensorB)
print(tensorA == tensorB) # will be true


Random Seed: 36 of type: <class 'int'>
tensor([[0.4978, 0.4356, 0.0132, 0.5109],
        [0.7582, 0.1383, 0.6524, 0.9391],
        [0.6839, 0.3550, 0.9829, 0.9012]])
tensor([[0.4978, 0.4356, 0.0132, 0.5109],
        [0.7582, 0.1383, 0.6524, 0.9391],
        [0.6839, 0.3550, 0.9829, 0.9012]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
